### ISSUE TITLE
Details of dependency parameter

### ISSUE THREAD

**Issue by webangon** [JoeSz/Exopite-Simple-Options-Framework#22]
My dependency does not work. What's wrong here?

'''

                array(
                'id'      => 'add',
                'type'    => 'button_bar',
                'title'   => 'Query',
                'options' => array(
                    'one'   => 'One',
                    'two'   => 'Two'
                ),
                'default' => 'one',
                ),

                array(
                    'id'     => 'text_er',
                    'type'   => 'text',
                    'title'  => 'Text Test Dependency',
                    'dependency' => array( 'add', '==', 'one' ),
                    'attributes'    => array(
                        'placeholder' => 'Dependency test',
                    ),
                ),

'''

**Comment by JoeSz** [comment]
Its look ok, but I need the whole config to test. 
It may take a while, because lately I have realtive little time. 
Maybe the "add" is a reserved word? Please try other IDs first.

You could try 'dependency' => array( 'add', 'any', 'one' ),

The framework uses jQuery Interdependencies:
https://github.com/miohtama/jquery-interdependencies
http://miohtama.github.io/jquery-interdependencies/

Maybe here can you find a soultion.

**Comment by JoeSz** [comment]
Did you try it or already solve it?
